import React from "react";
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";
import moment from "moment";

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 11,
  },
  mb2: {
    marginBottom: 20,
  },
  ms3: {
    marginLeft: 15
  },
  header: {
    fontSize: 16,
    textAlign: "center",
  },
  section: {
    marginBottom: 10,
  },
  label: {
    fontWeight: "bold",
  },
  hr: {
    borderBottom: 1
  },
  footer: {
    marginTop: 30,
    fontSize: 10,
    textAlign: "center",
    color: "#555",
  },
});

const AlumniReport = ({ user, generatedBy }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.mb2}>
        <Text style={styles.header}>Pangasinan State University - San Carlos City Campus</Text>
        <Text style={styles.header}>Alumni Report</Text>
      </View>
      <View style={[styles.section, styles.hr]}>
        <Text>
          <Text style={styles.label}>Name:</Text> {user?.first_name} {user?.last_name}
        </Text>
        <Text>
          <Text style={styles.label}>Email:</Text> {user?.email || "NA"}
        </Text>
        <Text>
          <Text style={styles.label}>Date of Birth:</Text>{" "}
          {user?.birthday ? new Date(user.birthday).toLocaleDateString() : "NA"}
        </Text>
        <Text>
          <Text style={styles.label}>Address:</Text> {user?.address || "NA"}
        </Text>
        <Text>
          <Text style={styles.label}>Course:</Text> {user?.course?.course_name || "NA"}
        </Text>
        <Text>
          <Text style={styles.label}>Batch:</Text> {user?.year || "NA"}
        </Text>
        <Text>
          <Text style={styles.label}>Current Employment Status:</Text>{" "}
          {user?.employment_status?.status?.status || "Unknown"}
        </Text>
      </View>
      <View style={[styles.label, styles.section]}>
        <Text style={[styles.label]}>Employment History:</Text>
      </View>
      <View style={[styles.section, styles.hr]}>
        {user?.statuses?.map(status => (
          <>
            <View style={[styles.mb2, styles.ms3]}>
              <Text>
                <Text style={styles.label}>Status:</Text>{status.status.status}
              </Text>
              {status.status.status == 'Employed' && (
                <>
                  <Text>
                    <Text style={styles.label}>Company:</Text>{status.answers.find(
                      (answer) => answer.employment_questions_ID === 3
                    )?.answer || "No answer available"}
                  </Text>
                  <Text>
                    <Text style={styles.label}>Type:</Text>{status.answers.find(
                      (answer) => answer.employment_questions_ID === 2
                    )?.answer || "No answer available"}
                  </Text>
                </>
              )}
              <Text>
                <Text style={styles.label}>Date:</Text>{moment(status.created_at).format('MMMM DD YYYY')}
              </Text>
            </View>
          </>
        ))}
      </View>
      <Text style={styles.footer}>
        Report auto-generated by {generatedBy || "System"} on {moment().format('MMMM DD YYYY, h:mm A')}.
      </Text>
    </Page>
  </Document>
);

export default AlumniReport;
