import React from "react";
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";
import moment from "moment";

const styles = StyleSheet.create({
  page: {
    padding: 20,
    fontSize: 11,
    backgroundColor: "#ffffff",
  },
  mb2: {
    marginBottom: 10,
  },
  header: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    color: "#333",
  },
  subheader: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
    color: "#444",
  },
  section: {
    marginBottom: 10,
  },
  table: {
    display: "table",
    width: "100%",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#000",
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: "row",
  },
  tableCol: {
    width: "60%",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#000",
    padding: 10,
  },
  tableHeader: {
    fontWeight: "bold",
    backgroundColor: "#f2f2f2",
  },
  footer: {
    marginTop: 30,
    fontSize: 10,
    textAlign: "center",
    color: "#888",
  },
});

const employmentData = [
  { question: "Employment Status", answer: ["Employed"] },
  { question: "Company", answer: ["bgry balya"] },
  { question: "Occupation", answer: ["Officials of Government and Special - Interest Organizations, Corporate Executive, Managers, Managing Proprietors and Supervisors"] },
  { question: "Employment Type", answer: ["Regular or Permanent"] },
  { question: "Business Industry", answer: ["Agriculture, Hunting, and Forestry"] },
  { question: "Place of Work", answer: ["Local"] },
  { question: "First Job After College", answer: ["Yes"] },
  { question: "Reasons for Staying", answer: ["Salaries and Benefits", "Related to course", "Peer influence"] },
  { question: "First Job Related to Course", answer: ["Yes"] },
  { question: "Reason for Accepting Job", answer: ["Salaries and Benefits"] },
  { question: "Reason for Changing Job", answer: ["Salaries and Benefits"] },
  { question: "Duration in First Job", answer: ["Less than a month"] },
  { question: "Job Search Method", answer: ["Response to an advertisement"] },
  { question: "Time Taken to Land First Job", answer: ["Less than a month"] },
  { question: "First Job Level", answer: ["Rank or Clerical"] },
  { question: "Present Job Level", answer: ["Self-employed"] },
  { question: "Initial Salary in First Job", answer: ["Below Php 5,000.00"] },
  { question: "College Curriculum Relevance", answer: ["Yes"] },
  { question: "Useful College Competencies", answer: ["Communication Skills", "Entrepreneurial Skills"] },
  { question: "Suggestions for Course Improvement", answer: ["N/A"] },
];

const AlumniDetailsReport = ({ user, generatedBy,data }) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Alumni Personal Information Section */}
        <View style={styles.mb2}>
          <Text style={styles.header}>Pangasinan State University - San Carlos City Campus</Text>
          <Text style={styles.header}>Alumni Report</Text>
        </View>

        {/* Personal Info Section */}
        <View style={styles.section}>
        <Text style={styles.subheader}>Personal Information</Text>
  <View style={styles.table}>
    <View style={styles.tableRow}>
      <Text style={[styles.tableCol, { width: "15%" }]}>Name:</Text>
      <Text style={[styles.tableCol, { width: "35%" }]}>{user?.first_name} {user?.middle_name} {user?.last_name}</Text>
      <Text style={[styles.tableCol, { width: "15%" }]}>Date of Birth:</Text>
      <Text style={[styles.tableCol, { width: "35%" }]}>{moment(user?.birthday, 'YYYY-MM-DD').format('MMMM DD YYYY')}</Text>
    </View>
    <View style={styles.tableRow}>
      <Text style={[styles.tableCol, { width: "15%" }]}>Email:</Text>
      <Text style={[styles.tableCol, { width: "35%" }]}>{user?.email}</Text>
      <Text style={[styles.tableCol, { width: "15%" }]}>Phone:</Text>
      <Text style={[styles.tableCol, { width: "35%" }]}>{user?.contact_number}</Text>
    </View>
    <View style={styles.tableRow}>
      <Text style={[styles.tableCol, { width: "15%" }]}>Address:</Text>
      <Text style={[styles.tableCol, { width: "85%" }]}>{user?.address}</Text>
    </View>
  </View>
</View>


        {/* Employment Information Section */}
        <View style={styles.section}>
          <Text style={styles.subheader}>Employment Information</Text>
          <View style={styles.table}>
            {data.map((item, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={[styles.tableCol, { width: "40%" }]}>{item.question}:</Text>
                <Text style={styles.tableCol}>{item.answer.join(", ")}</Text>
              </View>
            ))}
          </View>
        </View>

        <Text style={styles.footer}>
          Report auto-generated by {generatedBy || "System"} on {moment().format('MMMM DD YYYY, h:mm A')}.
        </Text>
      </Page>
    </Document>
  );
};

export default AlumniDetailsReport;
