import React from "react";
import { PDFViewer, Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";
import moment from "moment";

// Define styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 9,
  },
  p: {
    fontSize: 9,
  },
  mb2: {
    marginBottom: 20,
  },
  ms3: {
    marginLeft: 15,
  },
  hr: {
    borderBottom: 1,
  },
  header: {
    textAlign: "center",
    fontSize: 16,
  },
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: "row",
  },
  tableCol: {
    width: "20.6%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 3,
  },
  tableCell: {
    textAlign: "center",
  },
  footer: {
    marginTop: 20,
    fontSize: 10,
    textAlign: "center",
    color: "#555",
  },
});

// Define the PDF Document
const AnalyticsReport = ({ data, generatedBy, title }) => {
  // Group the data by the 'choices' field dynamically
  const groupedData = data.reduce((acc, row) => {
    
    const { choices } = row;
    if (!acc[choices]) {
      acc[choices] = [];
    }
    acc[choices].push(row);
    return acc;
  }, {});

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={[styles.mb2, styles.hr]}>
          <Text style={styles.header}>Pangasinan State University - San Carlos City Campus</Text>
          <Text style={[styles.header, styles.mb2]}>{title}</Text>
        </View>

        {/* Dynamically render tables for each unique choice */}
        {Object.keys(groupedData).map((choice, index) => (
          <React.Fragment key={index}>
            <Text style={styles.header}>{title=="IT-Related Jobs"?choice=="Yes"?"IT-Related":"Non-IT-Related":choice}</Text>
            <View style={styles.table}>
              <View style={styles.tableRow}>
                <View style={[styles.tableCol, { width: "4.6%" }]}>
                  <Text style={styles.tableCell}>No.</Text>
                </View>
                <View style={[styles.tableCol, { width: "8.6%" }]}>
                  <Text style={styles.tableCell}>Student ID</Text>
                </View>
                <View style={styles.tableCol}>
                  <Text style={styles.tableCell}>Name</Text>
                </View>
                <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Email</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Address</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Contact Number</Text>
          </View>
          <View style={[styles.tableCol,{width: "4.6%"}]}>
            <Text style={styles.tableCell}>Batch</Text>
          </View>
              </View>
              {groupedData[choice].map((row, index) => (
                <View style={styles.tableRow} key={index}>
                  <View style={[styles.tableCol, { width: "4.6%" }]}>
                    <Text style={styles.tableCell}>{index + 1}</Text>
                  </View>
                  <View style={[styles.tableCol, { width: "8.6%" }]}>
                    <Text style={styles.tableCell}>{row.student_id}</Text>
                  </View>
                  <View style={styles.tableCol}>
                    <Text style={styles.tableCell}>
                      {row.first_name} {row.middle_name} {row.last_name}
                    </Text>
                  </View>
                  <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.email}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.address}</Text>
            </View>
             <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.contact_number}</Text>
            </View>
            <View style={[styles.tableCol,{width: "4.6%"}]}>
              <Text style={styles.tableCell}>{row.year}</Text>
            </View>
                </View>
              ))}
            </View>
          </React.Fragment>
        ))}

        <Text style={styles.footer}>
          Report auto-generated by {generatedBy || "System"} on{" "}
          {moment().format("MMMM DD, YYYY, h:mm A")}.
        </Text>
      </Page>
    </Document>
  );
};

export default AnalyticsReport;
