import React from "react";
import { PDFViewer, Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";
import moment from "moment";

// Define styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 9,
  },
  mb2: {
    marginBottom: 20,
  },
  ms3: {
    marginLeft: 15,
  },
  hr: {
    borderBottom: 1,
  },
  header: {
    textAlign: "center",
    fontSize: 16,
  },
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    flexDirection: "row",
  },
  tableCol: {
    width: "14.2%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 3,
  },
  tableCell: {
    textAlign: "center",
  },
  footer: {
    marginTop: 20,
    fontSize: 10,
    textAlign: "center",
    color: "#555",
  },
});

// Define the PDF Document
const MasterListReport = ({ data, generatedBy }) => (
  <Document>
    <Page size="A4" orientation="landscape" style={styles.page}>
      <View style={[styles.mb2, styles.hr]}>
        <Text style={styles.header}>Pangasinan State University - San Carlos City Campus</Text>
        <Text style={[styles.header, styles.mb2]}>Alumni Report</Text>
      </View>
      <View style={styles.table}>
        {/* Table Header */}
        <View style={styles.tableRow}>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Full Name</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Student ID</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Birthday</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Email</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Address</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Contact Number</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableCell}>Employment Status</Text>
          </View>
        </View>
        {/* Table Rows */}
        {data.map((row, index) => (
          <View style={styles.tableRow} key={index}>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{`${row.first_name} ${row.last_name}`}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.student_ID}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{moment(row.birthday).format("MMMM DD, YYYY") || "NA"}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.email || "NA"}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.address || "NA"}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{row.contact_number || "NA"}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>
                {row.employment_status?.status?.status || "Never-Employed"}
              </Text>
            </View>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>
        Report auto-generated by {generatedBy || "System"} on{" "}
        {moment().format("MMMM DD, YYYY, h:mm A")}.
      </Text>
    </Page>
  </Document>
);

export default MasterListReport;
